openapi: 3.0.0
info:
  title: API de Gerenciamento de Alunos
  description: API para cadastro, listagem, busca e exclusão de alunos.
  version: "1.0"
servers:
  - url: http://localhost:5000
    description: Servidor local Flask

paths:
  /cadastrar_aluno:
    post:
      summary: Cadastrar um novo aluno
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                email:
                  type: string
                data_nascimento:
                  type: string
                  format: date
              required:
                - nome
                - email
                - data_nascimento
      responses:
        '201':
          description: Aluno cadastrado com sucesso
        '400':
          description: Requisição inválida

  /buscar_alunos:
    get:
      summary: Buscar todos os alunos
      responses:
        '200':
          description: Lista de alunos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    email:
                      type: string
                    data_nascimento:
                      type: string

  /buscar_aluno/{id}:
    get:
      summary: Buscar um aluno por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Dados do aluno
        '404':
          description: Aluno não encontrado

  /deletar_aluno/{id}:
    delete:
      summary: Deletar um aluno por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Aluno excluído com sucesso
        '404':
          description: Aluno não encontrado
